# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  $script = <<-SCRIPT
  echo "Starting Provisioning..."

  SCRIPT

  $script2 = <<-SCRIPT
  echo "Starting Provisioning..."

  SCRIPT

  Vagrant.configure("2") do |config|
     config.vm.define "smb2" do |smb2|
        smb2.vm.box="centos/7"
        smb2.vm.hostname="smbclient"
        smb2.vm.network "private_network", ip: "10.0.0.41"
        smb2.vm.provision "shell", inline: $script
      end

      config.vm.define "smb" do |smb|
        smb.vm.box="centos/7"
        smb.vm.hostname="smbsrv"
        smb.vm.network "private_network", ip: "10.0.0.40"
        smb.vm.provision "shell", inline: $script2
      end
  end
end
