# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$script = <<-SCRIPT
echo "Starting Provisioning..."

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.define "net" do |n|
        n.vm.box="generic/centos7"
        n.vm.hostname="networksrv"
        n.vm.network "private_network", ip: "10.5.0.10"
        n.vm.provision "shell", inline: $script
      end
end