# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script=<<-SCRIPT
sed -i s/SELINUX=enforcing/SELINUX=permissive/ /etc/selinux/config
yum update -y
yum install httpd -y
yum install php -y
yum install yum-utils -y
yum install createrepo -y

mkdir -p /var/www/html/pub/rhel7

SCRIPT

$script2=<<-SCRIPT2

yum update -y

sed -i s/SELINUX=enforcing/SELINUX=permissive/ /etc/selinux/config

echo "
[rhel7]
name = rhel-7-rpms
baseurl = http://10.0.1.100/pub/rhel7/
gpgcheck = 0
enabled = 1
" > /etc/yum.repos.d/private.repo
SCRIPT2

Vagrant.configure("2") do |config|
  config.vm.define "repo" do |r|
     r.vm.box="generic/centos7"
     r.vm.hostname="ansible"
     r.vm.network "private_network", ip: "10.0.1.100"
     r.vm.provision "shell", inline: $script
   end

   config.vm.define "client" do |c|
      c.vm.box="generic/centos7"
      c.vm.hostname="ansible"
      c.vm.network "private_network", ip: "10.0.1.101"
      c.vm.provision "shell", inline: $script
    end
end
