# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script=<<-SCRIPT
sed -i s/SELINUX=enforcing/SELINUX=permissive/ /etc/selinux/config
yum update -y
yum install httpd -y
yum install php -y
yum install yum-utils -y
yum install createrepo -y


mkdir -p /var/www/html/pub/rhel7

echo "
[rhel7]
name = rhel-7-rpms
baseurl = http://10.0.1.100/rhel6/server
gpgcheck = 0
enabled = 1
" > /etc/yum.repos.d/private.repo


SCRIPT


Vagrant.configure("2") do |config|
  config.vm.define "repo" do |r|
     r.vm.box="centos/7"
     r.vm.hostname="ansible"
     r.vm.network "private_network", ip: "10.0.1.100"
     r.vm.provision "shell", inline: $script
   end
end
