# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ans" do |ans|
     ans.vm.box="centos/7"
     ans.vm.hostname="ldap1"
     ans.vm.network "private_network", ip: "10.0.200.100"
     ans.vm.provision "shell", inline: $script
   end

   config.vm.define "web" do |web|
      web.vm.box="centos/7"
      web.vm.hostname="web"
      web.vm.network "private_network", ip: "10.0.200.100"
      web.vm.provision "shell", inline: $web_script
    end

    config.vm.define "db" do |db|
       db.vm.box="centos/7"
       db.vm.hostname="db"
       db.vm.network "private_network", ip: "10.0.200.100"
       db.vm.provision "shell", inline: $db_script
     end
end
