# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script = <<-SCRIPT
echo "Starting Provisioning..."
yum -y install ipa-server.x86_64
yum -y install ipa-server-dns.noarch
yum -y install ipa-server-trust-ad.x86_64
yum -y install ipa-client
yum -y install memcached

sleep 2
echo "10.0.10.110 ldap1.example.com ldap1" >> /etc/hosts
echo "10.0.10.111 ldap2.example.com ldap2" >> /etc/hosts
echo "10.0.10.112 client.example.com client" >> /etc/hosts
sleep 2
#ipa-server-install
SCRIPT

$client_script = <<-SCRIPT
echo "Starting Provisioning..."
yum -y install ipa-client
sleep 2
echo "10.0.10.110 ldap1.example.com ldap1" >> /etc/hosts
echo "10.0.10.111 ldap2.example.com ldap2" >> /etc/hosts
echo "10.0.10.112 client.example.com client" >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "ipa" do |ipa|
     ipa.vm.box="centos/7"
     ipa.vm.hostname="freeipasrv"
     ipa.vm.network "private_network", ip: "10.0.10.110"
     ipa.vm.network "forwarded_port" guest:80, host:8080
     ipa.vm.network "forwarded_port" guest:443, host:8043
     ipa.vm.provision "shell", inline: $script
   end

   config.vm.define "ipa2" do |ipa2|
      ipa2.vm.box="centos/7"
      ipa2.vm.hostname="freeipasrv2"
      ipa2.vm.network "private_network", ip: "10.0.10.111"
      ipa.vm.network "forwarded_port" guest:80, host:8080
      ipa.vm.network "forwarded_port" guest:443, host:8043
      ipa2.vm.provision "shell", inline: $script
    end

    config.vm.define "ipa3" do |ipa3|
       ipa3.vm.box="centos/7"
       ipa3.vm.hostname="freeipaclient"
       ipa3.vm.network "private_network", ip: "10.0.10.112"
       ipa3.vm.provision "shell", inline: $client_script
     end
end
