# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script =<<-SCRIPT

yum localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm
yum update -y

yum groupinstall "Development tools" ""

SCRIPT
Vagrant.configure("2") do |config|

  config.vm.define "build" do |b|
    b.vm.box="centos/7"
    b.vm.hostname="ansible"
    b.vm.network "private_network", ip: "10.0.1.100"
    b.vm.synced_folder "./sources", "/home/vagrant/sources"

end
