# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "fw" do |fw|
      fw.vm.box="centos/7"
      fw.vm.hostname="fw"
      fw.vm.network "private_network", ip: "10.0.2.20"
      #fw.vm.provision "shell", inline: $script
    end

    config.vm.define "c" do |c|
      c.vm.box="centos/7"
      c.vm.hostname="client"
      c.vm.network "private_network", ip: "10.0.2.21"
      #c.vm.provision "shell", inline: $script2
    end
end
